[
  {
    "test_name": "test_Bay_stock_in",
    "status": "PASS",
    "message": "테스트 성공",
    "timestamp": "2025-04-15 18:53:57",
    "file": "tests/test_Bay_stock_in.py",
    "stack": ""
  },
  {
    "test_name": "test_Bay_stock_out",
    "status": "FAIL",
    "message": "Command '['pytest', 'tests/test_Bay_stock_out.py', '--json-report', '--json-report-file=scripts/result.json']' returned non-zero exit status 1.",
    "timestamp": "2025-04-15 18:54:40",
    "file": "tests/test_Bay_stock_out.py",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\kjeon\\OneDrive\\Desktop\\QA\\자동화\\scripts\\run_tests_and_generate_json.py\", line 95, in <module>\n    result = subprocess.run([\n        \"pytest\",\n    ...<2 lines>...\n        f\"--json-report-file={JSON_REPORT_FILE}\"\n    ], check=True)\n  File \"C:\\Users\\kjeon\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\subprocess.py\", line 579, in run\n    raise CalledProcessError(retcode, process.args,\n                             output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command '['pytest', 'tests/test_Bay_stock_out.py', '--json-report', '--json-report-file=scripts/result.json']' returned non-zero exit status 1.\n"
  },
  {
    "test_name": "test_Bay_order_status_request_cancel",
    "status": "PASS",
    "message": "테스트 성공",
    "timestamp": "2025-04-15 18:54:48",
    "file": "tests/test_Bay_order_status_request_cancel.py",
    "stack": ""
  },
  {
    "test_name": "test_Bay_order_status_request",
    "status": "FAIL",
    "message": "Command '['pytest', 'tests/test_Bay_order_status_request.py', '--json-report', '--json-report-file=scripts/result.json']' returned non-zero exit status 1.",
    "timestamp": "2025-04-15 18:54:51",
    "file": "tests/test_Bay_order_status_request.py",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\kjeon\\OneDrive\\Desktop\\QA\\자동화\\scripts\\run_tests_and_generate_json.py\", line 95, in <module>\n    result = subprocess.run([\n        \"pytest\",\n    ...<2 lines>...\n        f\"--json-report-file={JSON_REPORT_FILE}\"\n    ], check=True)\n  File \"C:\\Users\\kjeon\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\subprocess.py\", line 579, in run\n    raise CalledProcessError(retcode, process.args,\n                             output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command '['pytest', 'tests/test_Bay_order_status_request.py', '--json-report', '--json-report-file=scripts/result.json']' returned non-zero exit status 1.\n"
  },
  {
    "test_name": "test_Bay_order_status_progress_delivery",
    "status": "FAIL",
    "message": "Command '['pytest', 'tests/test_Bay_order_status_progress_delivery.py', '--json-report', '--json-report-file=scripts/result.json']' returned non-zero exit status 1.",
    "timestamp": "2025-04-15 18:54:53",
    "file": "tests/test_Bay_order_status_progress_delivery.py",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\kjeon\\OneDrive\\Desktop\\QA\\자동화\\scripts\\run_tests_and_generate_json.py\", line 95, in <module>\n    result = subprocess.run([\n        \"pytest\",\n    ...<2 lines>...\n        f\"--json-report-file={JSON_REPORT_FILE}\"\n    ], check=True)\n  File \"C:\\Users\\kjeon\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\subprocess.py\", line 579, in run\n    raise CalledProcessError(retcode, process.args,\n                             output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command '['pytest', 'tests/test_Bay_order_status_progress_delivery.py', '--json-report', '--json-report-file=scripts/result.json']' returned non-zero exit status 1.\n"
  },
  {
    "test_name": "test_Bay_order_status_progress_complete",
    "status": "FAIL",
    "message": "Command '['pytest', 'tests/test_Bay_order_status_progress_complete.py', '--json-report', '--json-report-file=scripts/result.json']' returned non-zero exit status 1.",
    "timestamp": "2025-04-15 18:54:55",
    "file": "tests/test_Bay_order_status_progress_complete.py",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\kjeon\\OneDrive\\Desktop\\QA\\자동화\\scripts\\run_tests_and_generate_json.py\", line 95, in <module>\n    result = subprocess.run([\n        \"pytest\",\n    ...<2 lines>...\n        f\"--json-report-file={JSON_REPORT_FILE}\"\n    ], check=True)\n  File \"C:\\Users\\kjeon\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\subprocess.py\", line 579, in run\n    raise CalledProcessError(retcode, process.args,\n                             output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command '['pytest', 'tests/test_Bay_order_status_progress_complete.py', '--json-report', '--json-report-file=scripts/result.json']' returned non-zero exit status 1.\n"
  },
  {
    "test_name": "test_Bay_order_status_delivery",
    "status": "FAIL",
    "message": "Command '['pytest', 'tests/test_Bay_order_status_delivery.py', '--json-report', '--json-report-file=scripts/result.json']' returned non-zero exit status 1.",
    "timestamp": "2025-04-15 18:54:58",
    "file": "tests/test_Bay_order_status_delivery.py",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\kjeon\\OneDrive\\Desktop\\QA\\자동화\\scripts\\run_tests_and_generate_json.py\", line 95, in <module>\n    result = subprocess.run([\n        \"pytest\",\n    ...<2 lines>...\n        f\"--json-report-file={JSON_REPORT_FILE}\"\n    ], check=True)\n  File \"C:\\Users\\kjeon\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\subprocess.py\", line 579, in run\n    raise CalledProcessError(retcode, process.args,\n                             output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command '['pytest', 'tests/test_Bay_order_status_delivery.py', '--json-report', '--json-report-file=scripts/result.json']' returned non-zero exit status 1.\n"
  },
  {
    "test_name": "test_Bay_order_status_complete",
    "status": "FAIL",
    "message": "Command '['pytest', 'tests/test_Bay_order_status_complete.py', '--json-report', '--json-report-file=scripts/result.json']' returned non-zero exit status 1.",
    "timestamp": "2025-04-15 18:55:01",
    "file": "tests/test_Bay_order_status_complete.py",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\kjeon\\OneDrive\\Desktop\\QA\\자동화\\scripts\\run_tests_and_generate_json.py\", line 95, in <module>\n    result = subprocess.run([\n        \"pytest\",\n    ...<2 lines>...\n        f\"--json-report-file={JSON_REPORT_FILE}\"\n    ], check=True)\n  File \"C:\\Users\\kjeon\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\subprocess.py\", line 579, in run\n    raise CalledProcessError(retcode, process.args,\n                             output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command '['pytest', 'tests/test_Bay_order_status_complete.py', '--json-report', '--json-report-file=scripts/result.json']' returned non-zero exit status 1.\n"
  },
  {
    "test_name": "test_Bay_order_status_fail",
    "status": "FAIL",
    "message": "Command '['pytest', 'tests/test_Bay_order_status_fail.py', '--json-report', '--json-report-file=scripts/result.json']' returned non-zero exit status 1.",
    "timestamp": "2025-04-15 18:55:06",
    "file": "tests/test_Bay_order_status_fail.py",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\kjeon\\OneDrive\\Desktop\\QA\\자동화\\scripts\\run_tests_and_generate_json.py\", line 95, in <module>\n    result = subprocess.run([\n        \"pytest\",\n    ...<2 lines>...\n        f\"--json-report-file={JSON_REPORT_FILE}\"\n    ], check=True)\n  File \"C:\\Users\\kjeon\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\subprocess.py\", line 579, in run\n    raise CalledProcessError(retcode, process.args,\n                             output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command '['pytest', 'tests/test_Bay_order_status_fail.py', '--json-report', '--json-report-file=scripts/result.json']' returned non-zero exit status 1.\n"
  }
]